version: '3.8'  # Optional, but can be included for clarity

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - some-postgres
      - server
      - client
    networks:
      - pg_network

  some-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg_network

  server:
    build: 
      context: ./server  
      dockerfile: Dockerfile  
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      CLIENT_URL: ${CLIENT_URL}
    container_name: server-chat
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app  
      - /usr/src/app/node_modules  
    networks:
      - pg_network  

  client:
    build: 
      context: ./client  
      dockerfile: Dockerfile  
    container_name: client-chat
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app  
      - /app/node_modules  
    environment:
      - VITE_SERVER_PORT=http://localhost:3001  
      - VITE_CLIENT_PORT=3000
    networks:
      - pg_network

volumes:
  postgres_data:
  node_modules: {}  

networks:
  pg_network: