version: '3.8'  # Optional, but can be included for clarity

services:
  some-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: kirill-kent2006@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg_network

  server:
    build: 
      context: ./server  
      dockerfile: Dockerfile  
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      CLIENT_URL: ${CLIENT_URL}
    container_name: server-chat
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app  
    networks:
      - pg_network  

  client:
    build: 
      context: ./client  
      dockerfile: Dockerfile  
    container_name: client-chat
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app 
      - node_modules:/app/node_modules  # Используйте именованный том вместо прямого монтирования
    environment:
      - VITE_DEV_PORT=http://localhost:3001  
    networks:
      - pg_network

volumes:
  postgres_data:
  node_modules: {}  # Определение именованного тома для node_modules

networks:
  pg_network: